name: Publish Library

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Library version (e.g. 0.1.0)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: latest

      - name: Build
        run: odin build .

      - name: Test
        run: ./rbs test

      - name: Install library
        run: ./rbs install ci

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: rbs-v${{ inputs.version }}
          path: bin
          if-no-files-found: error
